# this loads the Facebook API

window.fbAsyncInit = ->
    FB.init
        appId: '1668145613237422'
        xfbml: true
        version: 'v2.10'
    FB.AppEvents.logPageView()
    return

((d, s, id) ->
    js = undefined
    fjs = d.getElementsByTagName(s)[0]
    if d.getElementById(id)
        return
    js = d.createElement(s)
    js.id = id
    js.src = '//connect.facebook.net/en_US/sdk.js'
    fjs.parentNode.insertBefore js, fjs
    return
) document, 'script', 'facebook-jssdk'
# FB Share with custom OG data.
(($) ->
    $('.fb-share-btn').on 'click', (event) ->
        event.preventDefault()
        event.stopPropagation()
        event.stopImmediatePropagation()
        # Dynamically gather and set the FB share data.
        FBDesc = 'TestSharing for a Superduper Facebook App.'
        FBTitle = 'TestSharing'
        FBLink = "#{location.href}?fb_share=1"
        FBPic = "../images/world_map.jpg"
        # Open FB share popup
        FB.ui {
            method: 'share_open_graph'
            action_type: 'og.shares'
            action_properties: JSON.stringify(object:
                'og:url': FBLink
                'og:title': FBTitle
                'og:description': FBDesc
                'og:image': FBPic)
        }, (response) ->
            # Action after response
            return
        return
    return
) jQuery

# ---
# generated by js2coffee 2.2.0
